function Y = YFun(g,in2,in3,in4,in5,in6,in7,in8)
%YFun
%    Y = YFun(G,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Jan-2023 13:28:52

% Code generated by file 'LiveEditorEvaluationHelperE1357067292'.
% Model: YFun
% Inputs: g, i_g, r_P1P2, r_P2P3, r_P3P4, theta, omega, domega
%
%
domega_l1 = in8(1,:);
domega_l2 = in8(2,:);
domega_m1 = in8(4,:);
domega_l3 = in8(3,:);
domega_m2 = in8(5,:);
domega_m3 = in8(6,:);
i_g1 = in2(1,:);
i_g2 = in2(2,:);
i_g3 = in2(3,:);
omega_l1 = in7(1,:);
omega_l2 = in7(2,:);
omega_l3 = in7(3,:);
r_P1P21 = in3(1,:);
r_P1P22 = in3(2,:);
r_P2P31 = in4(1,:);
r_P2P32 = in4(2,:);
r_P2P33 = in4(3,:);
theta_l2 = in6(2,:);
theta_l3 = in6(3,:);
t2 = cos(theta_l2);
t3 = cos(theta_l3);
t4 = sin(theta_l2);
t5 = sin(theta_l3);
t6 = domega_l2+domega_l3;
t7 = omega_l2+omega_l3;
t8 = theta_l2+theta_l3;
t9 = omega_l1.^2;
t10 = omega_l2.^2;
t11 = theta_l2.*2.0;
t12 = theta_l3.*2.0;
t23 = -r_P1P21;
t24 = -r_P2P33;
t13 = cos(t11);
t14 = sin(t11);
t15 = r_P2P31.*t3;
t16 = r_P2P32.*t2;
t17 = r_P2P32.*t3;
t18 = cos(t8);
t19 = r_P2P31.*t4;
t20 = r_P2P31.*t5;
t21 = r_P2P32.*t5;
t22 = sin(t8);
t25 = t8+theta_l2;
t38 = r_P1P22+t24;
t40 = t8.*2.0;
t26 = cos(t25);
t27 = sin(t25);
t28 = domega_l1.*t18;
t29 = g.*t18;
t30 = omega_l2.*t18;
t31 = omega_l3.*t18;
t32 = r_P1P21.*t18;
t33 = domega_l1.*t22;
t34 = g.*t22;
t35 = omega_l2.*t22;
t36 = omega_l3.*t22;
t37 = r_P1P21.*t22;
t39 = -t20;
t51 = cos(t40);
t53 = sin(t40);
t54 = t18.*t23;
t57 = t15+t21;
t67 = t16+t19+t23;
t41 = omega_l1.*t32;
t42 = r_P1P22.*t30;
t43 = r_P1P22.*t31;
t44 = r_P2P33.*t30;
t45 = r_P2P33.*t31;
t46 = omega_l1.*t37;
t47 = r_P1P22.*t35;
t48 = r_P1P22.*t36;
t49 = r_P2P33.*t35;
t50 = r_P2P33.*t36;
t52 = -t29;
t55 = -t33;
t56 = -t34;
t58 = omega_l1.*t54;
t61 = t17+t39;
t62 = t28.*t38;
t63 = t33.*t38;
t64 = t9.*t51;
t65 = t30+t31;
t66 = t35+t36;
t69 = (t9.*t53)./2.0;
t59 = -t47;
t60 = -t48;
t68 = t38.*t55;
mt1 = [domega_l1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,domega_m1.*i_g1.^2,0.0,0.0,domega_l1.*t2.^2-omega_l1.*omega_l2.*t14,(t9.*t14)./2.0,0.0,0.0,0.0,0.0,domega_l1.*t2.*t4.*-2.0-omega_l1.*omega_l2.*t13.*2.0,t9.*t13,0.0,0.0,0.0,0.0,domega_l2.*t2-t4.*t10,domega_l1.*t2,0.0,0.0,0.0,0.0,-domega_l2.*t4-t2.*t10,-domega_l1.*t4,0.0,0.0,0.0,0.0,0.0,domega_l2,0.0,0.0,0.0,0.0,-omega_l2.*(omega_l1.*r_P1P21.*t2+omega_l2.*r_P1P22.*t4)-domega_l1.*r_P1P21.*t4.*2.0+domega_l2.*r_P1P22.*t2+omega_l1.*omega_l2.*t2.*t23,-g.*t4+domega_l1.*r_P1P22.*t2+r_P1P21.*t2.*t9,0.0,0.0,0.0,0.0,omega_l2.*(omega_l1.*r_P1P21.*t4-omega_l2.*r_P1P22.*t2)-domega_l1.*r_P1P21.*t2.*2.0-domega_l2.*r_P1P22.*t4+omega_l1.*omega_l2.*r_P1P21.*t4,-g.*t2-domega_l1.*r_P1P22.*t4+t4.*t9.*t23,0.0,0.0,0.0,0.0,0.0,0.0];
mt2 = [0.0,0.0,domega_m2.*i_g2.^2,0.0,t18.*t28-omega_l1.*((omega_l2.*t53)./2.0+(omega_l3.*t53)./2.0)-(omega_l1.*omega_l2.*t53)./2.0-(omega_l1.*omega_l3.*t53)./2.0,t69,t69,0.0,0.0,0.0,t22.*t28.*-2.0-omega_l1.*(omega_l2.*t51+omega_l3.*t51)-omega_l1.*omega_l2.*t51-omega_l1.*omega_l3.*t51,t64,t64,0.0,0.0,0.0,domega_l2.*t18+domega_l3.*t18-omega_l2.*t66-omega_l3.*t66,t28,t28,0.0,0.0,0.0,-domega_l2.*t22-domega_l3.*t22-omega_l2.*t65-omega_l3.*t65,t55,t55,0.0,0.0,0.0,0.0,t6,t6,0.0,0.0,0.0];
mt3 = [omega_l1.*((omega_l3.*t17)./2.0-(omega_l3.*t20)./2.0+t23.*t30+t23.*t31+omega_l2.*r_P2P31.*t27+omega_l2.*r_P2P32.*t26+(omega_l3.*r_P2P31.*t27)./2.0+(omega_l3.*r_P2P32.*t26)./2.0)+t33.*t67.*2.0+omega_l3.*(t49+t50+t58+t59+t60+(omega_l1.*t17)./2.0-(omega_l1.*t20)./2.0+(omega_l1.*r_P2P31.*t27)./2.0+(omega_l1.*r_P2P32.*t26)./2.0)+omega_l2.*(t49+t50+t58+t59+t60+omega_l1.*r_P2P31.*t27+omega_l1.*r_P2P32.*t26)+domega_l2.*t18.*t38+domega_l3.*t18.*t38,t56+t62-t9.*(t54+r_P2P31.*t27+r_P2P32.*t26)+domega_l2.*t57.*2.0+domega_l3.*t57+omega_l2.*omega_l3.*t61+omega_l3.*t7.*t61,t56+t62+domega_l2.*t57-t10.*t61-t9.*(t17./2.0-t20./2.0+t54+(r_P2P31.*t27)./2.0+(r_P2P32.*t26)./2.0),0.0,0.0,0.0];
mt4 = [-omega_l1.*((omega_l3.*t15)./2.0+(omega_l3.*t21)./2.0+t23.*t35+t23.*t36-omega_l2.*r_P2P31.*t26-(omega_l3.*r_P2P31.*t26)./2.0+omega_l2.*r_P2P32.*t27+(omega_l3.*r_P2P32.*t27)./2.0)+t28.*t67.*2.0-omega_l3.*(t42+t43+(omega_l1.*t15)./2.0+(omega_l1.*t21)./2.0+t24.*t30+t24.*t31-(omega_l1.*r_P2P31.*t26)./2.0+(omega_l1.*r_P2P32.*t27)./2.0+omega_l1.*t22.*t23)+omega_l2.*(-t42-t43+t44+t45+t46+omega_l1.*r_P2P31.*t26-omega_l1.*r_P2P32.*t27)-domega_l2.*t22.*t38-domega_l3.*t22.*t38,t52+t68-t9.*(t37+r_P2P31.*t26-r_P2P32.*t27)+domega_l3.*t61+domega_l2.*(t17.*2.0-t20.*2.0)-omega_l2.*omega_l3.*t57-omega_l3.*t7.*t57];
mt5 = [t52+t68+domega_l2.*t61+t10.*t57+t9.*(t15./2.0+t21./2.0-(r_P2P31.*t26)./2.0+(r_P2P32.*t27)./2.0+t22.*t23),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,domega_m3.*i_g3.^2];
Y = reshape([mt1,mt2,mt3,mt4,mt5],6,18);
