function u = gravityCompensation_fun(g,in2,in3,in4,in5,in6)
%gravityCompensation_fun
%    U = gravityCompensation_fun(G,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    11-Jan-2023 09:46:35

% Code generated by file 'LiveEditorEvaluationHelperE1455415238'.
% Model: gravityCompensation_fun
% Inputs: g, r_P1P2, r_P2P3, r_P3P4, baseParam, thetaLoad
%
%
baseParam8 = in5(8,:);
baseParam9 = in5(9,:);
baseParam16 = in5(16,:);
baseParam17 = in5(17,:);
theta_l2 = in6(2,:);
theta_l3 = in6(3,:);
t2 = theta_l2+theta_l3;
t3 = cos(t2);
t4 = sin(t2);
t5 = baseParam17.*g.*t3;
t6 = baseParam16.*g.*t4;
t7 = -t5;
t8 = -t6;
u = [0.0;t7+t8-baseParam9.*g.*cos(theta_l2)-baseParam8.*g.*sin(theta_l2);t7+t8];
