function tauMotor = inverseDynamicsMotor_disObserver_reduced_fun(in1,in2,in3,in4)
%inverseDynamicsMotor_disObserver_reduced_fun
%    tauMotor = inverseDynamicsMotor_disObserver_reduced_fun(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    11-Jan-2023 09:46:25

% Code generated by file 'LiveEditorEvaluationHelperE1455415238'.
% Model: inverseDynamicsMotor_disObserver_reduced_fun
% Inputs: i_g, baseParam, domegaMotor, tauE
%
%
baseParam2 = in2(2,:);
baseParam10 = in2(10,:);
baseParam18 = in2(18,:);
domega_m1 = in3(1,:);
domega_m2 = in3(2,:);
domega_m3 = in3(3,:);
i_g1 = in1(1,:);
i_g2 = in1(2,:);
i_g3 = in1(3,:);
tauE1 = in4(1,:);
tauE2 = in4(2,:);
tauE3 = in4(3,:);
tauMotor = [tauE1+baseParam2.*domega_m1.*i_g1.^2;tauE2+baseParam10.*domega_m2.*i_g2.^2;tauE3+baseParam18.*domega_m3.*i_g3.^2];
