function tauMotor = inverseDynamics_reduced_fun(g,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%inverseDynamics_reduced_fun
%    tauMotor = inverseDynamics_reduced_fun(G,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    11-Jan-2023 09:46:14

% Code generated by file 'LiveEditorEvaluationHelperE1455415238'.
% Model: inverseDynamics_reduced_fun
% Inputs: g, i_g, r_P1P2, r_P2P3, r_P3P4, baseParam, theta, omega, tauE, tauF, u
%
%
baseParam2 = in6(2,:);
baseParam10 = in6(10,:);
baseParam18 = in6(18,:);
domega_m1 = in9(4,:);
domega_m2 = in9(5,:);
domega_m3 = in9(6,:);
i_g1 = in2(1,:);
i_g2 = in2(2,:);
i_g3 = in2(3,:);
tauE1 = in10(1,:);
tauE2 = in10(2,:);
tauF1 = in11(1,:);
tauE3 = in10(3,:);
tauF2 = in11(2,:);
tauF3 = in11(3,:);
tauMotor = [tauE1+tauF1+baseParam2.*domega_m1.*i_g1.^2;tauE2+tauF2+baseParam10.*domega_m2.*i_g2.^2;tauE3+tauF3+baseParam18.*domega_m3.*i_g3.^2];
