function hdError = kinError_periodic_axis1_fun(in1,x)
%kinError_periodic_axis1_fun
%    hdError = kinError_periodic_axis1_fun(IN1,X)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    15-Dec-2022 16:58:36

% Code generated by file 'LiveEditorEvaluationHelperE449172899'.
% Model: kinError_periodic_axis1_fun
% Inputs: coeffs, theta
%
%
cCos1 = in1(1,:);
cCos2 = in1(2,:);
cCos3 = in1(3,:);
cSin1 = in1(4,:);
cSin2 = in1(5,:);
cSin3 = in1(6,:);
t2 = x.*pi.*(8.0./3.0);
t3 = x.*pi.*(1.6e+1./9.0);
t4 = x.*pi.*(3.2e+1./9.0);
hdError = cCos1.*cos(t3)+cCos2.*cos(t2)+cCos3.*cos(t4)+cSin1.*sin(t3)+cSin2.*sin(t2)+cSin3.*sin(t4);
